import { StyleSheet } from "react-native";
import { colors, fontSize } from "../../styles/hicity.styles";

const styles = StyleSheet.create({
  containerMain: {
    height: "100%",
    backgroundColor: colors.white,
  },
  container: {
    alignItems: "center",
    marginBottom: 100,
  },
  dataContainer: {
    flex: 1,
    alignItems: "center",
    top: 70,
  },
  form: { marginTop: 50 },
  input: {
    height: 40,
    margin: 0,
    borderWidth: 1,
    padding: 10,
    width: 320,
    borderColor: colors.white,
    borderBottomColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
  },
  inputMultiline: {
    minHeight: 100,
    margin: 0,
    borderWidth: 1,
    padding: 10,
    width: 320,
    marginTop: 5,
    borderColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
  },
  inputMapaContainer: {
    height: 60,
    borderWidth: 1,
    padding: 10,
    width: 320,
    borderColor: colors.white,
    borderBottomColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
    justifyContent: "center",
  },
  inputMapa: {
    color: colors.yellow,
    fontSize: fontSize.text,
    fontWeight: "600",
  },
  textInfo: {
    color: colors.grey,
    fontSize: fontSize.text,
    marginTop: 3,
  },
  picker: {
    margin: 0,
    borderWidth: 1,
    padding: 10,
    width: 320,
    borderColor: colors.white,
    borderBottomColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
  },
  inputMultilineDescription: {
    minHeight: 250,
    margin: 0,
    borderWidth: 1,
    padding: 10,
    width: 320,
    marginTop: 5,
    borderColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
  },
  label: {
    fontSize: fontSize.text,
    marginTop: 15,
    color: colors.darkGrey,
  },
  title: {
    fontSize: fontSize.h1,
    color: colors.yellow,
    fontWeight: "600",
    marginBottom: 5,
  },
  buttonContainer: {
    alignItems: "flex-end",
    width: 320,
  },
  button: {
    width: 150,
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    borderRadius: 90,
    backgroundColor: colors.yellow,
    padding: 10,
    marginTop: 20,
  },
  buttonDisabled: {
    width: 150,
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    borderRadius: 90,
    backgroundColor: colors.lightYellow,
    padding: 10,
    marginTop: 20,
  },
  buttonText: {
    color: colors.white,
    fontSize: fontSize.textButton,
    fontWeight: "600",
  },
  titleContainer: {
    width: 320,
  },
  mapButtonContainer: {
    flexDirection: "row",
    width: 380,
    justifyContent: "space-between",
  },
  inputGalleryContainer: {
    height: 150,
    borderWidth: 1,
    padding: 10,
    width: 320,
    borderColor: colors.white,
    borderBottomColor: colors.grey,
    fontSize: fontSize.text,
    paddingHorizontal: 0,
    color: colors.grey,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },

  map: {
    width: 380,
    height: 600,
    borderRadius: 20,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
    overflow: "hidden",
    shadowColor: colors.black,
    backgroundColor: "rgba(255,255,255,0.5)",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  miniatureStyle: {
    width: 90,
    height: 90,
    marginBottom: 8,
  },
  containerIcon: {
    alignItems: "center",
    justifyContent: "center",
    height: 90,
    width: 90,
    marginBottom: 8,
    backgroundColor: colors.lightYellow,
  },
});
export default styles;
